const HUGO_TITLES: Record<string, string> = {
  "a-lydie.txt": "À Lydie",
  "a-madame-la-generale-lucotte.txt": "A Madame la Générale Lucotte",
  "achemenide.txt": "Achéménide",
  "actes-et-paroles-i-avant-lexil-1841-1852.txt": "Actes et Paroles I Avant L’exil 1841-1852",
  "actes-et-paroles-ii-pendant-lexil-1852-1870.txt": "Actes et Paroles II Pendant L’exil 1852-1870",
  "actes-et-paroles-iii-depuis-lexil-1870-1876.txt": "Actes et Paroles III Depuis L’exil 1870-1876",
  "actes-et-paroles-iv-depuis-lexil-1876-1885.txt": "Actes et Paroles IV Depuis L’exil 1876-1885",
  "amy-robsart.txt": "Amy Robsart",
  "angelo-tyran-de-padoue.txt": "Angelo Tyran de Padoue",
  "belgique.txt": "Belgique",
  "bonheur-que-procure-letude.txt": "Bonheur que Procure l'Étude",
  "bretagne-et-normandie-1.txt": "Bretagne et Normandie 1",
  "bretagne-et-normandie-2.txt": "Bretagne et Normandie 2",
  "bug-jargal.txt": "Bug-jargal",
  "cahier-complementaire-a-histoire-dun-crime.txt": "Cahier Complémentaire à Histoire D’un Crime",
  "ce-que-jaime.txt": "Ce que J’aime",
  "cesar-passe-le-rubicon.txt": "César Passe le Rubicon",
  "choses-vues.txt": "Choses Vues",
  "claude-gueux.txt": "Claude Gueux",
  "correspondance-1814-1848.txt": "Correspondance 1814 – 1848",
  "correspondance-1849-1868.txt": "Correspondance 1849 – 1868",
  "cromwell.txt": "Cromwell",
  "derniere-gerbe.txt": "Dernière Gerbe",
  "dieu.txt": "Dieu",
  "discours-a-lassemblee-nationale.txt": "Discours a L’assemblée Nationale",
  "discours-douverture-du-congres-litteraire-international.txt": "Discours D’ouverture du Congrès Littéraire International",
  "discours-sur-les-avantages-de-lenseignement-mutuel.txt": "Discours sur les Avantages de L’enseignement Mutuel",
  "epitre-a-brutus.txt": "Épître à Brutus",
  "etre-aime.txt": "Être Aimé",
  "fragments-dun-voyage-aux-alpes.txt": "Fragments D’un Voyage aux Alpes",
  "fragments-philosophiques-des-annees-1860-1865.txt": "Fragments Philosophiques des Années 1860-1865",
  "funerailles-de-lempereur.txt": "Funérailles de L’empereur",
  "han-dislande.txt": "Han D’islande",
  "hernani.txt": "Hernani",
  "histoire-dun-crime.txt": "Histoire D’un Crime",
  "idylle.txt": "Idylle",
  "imitation-dowen.txt": "Imitation D’owen",
  "inez-de-castro.txt": "Inez de Castro",
  "la-canadienne.txt": "La Canadienne",
  "la-esmeralda.txt": "La Esmeralda",
  "la-fin-de-satan.txt": "La Fin de Satan",
  "la-foret-mouillee.txt": "La Forêt Mouillée",
  "la-grandmere.txt": "La Grand’mère",
  "la-legende-des-siecles.txt": "La Légende des Siècles",
  "la-liberte-de-la-presse.txt": "La Liberté de la Presse",
  "la-liberte-de-lenseignement.txt": "La Liberté de L’enseignement",
  "la-liberte-du-theatre.txt": "La Liberté du Théâtre",
  "la-loi-sur-la-deportation.txt": "La Loi sur la Déportation",
  "la-misere.txt": "La Misère",
  "la-pitie-supreme.txt": "La Pitié Suprême",
  "la-servilite-de-la-magistrature-imperiale.txt": "La Servilité de la Magistrature Impériale",
  "la-voix-de-guernesey.txt": "La Voix de Guernesey",
  "labolition-de-la-peine-de-mort.txt": "L’abolition de la Peine de Mort",
  "lane.txt": "L’âne",
  "lannee-terrible.txt": "L’année Terrible",
  "lantre-des-cyclopes.txt": "L’antre des Cyclopes",
  "larchipel-de-la-manche.txt": "L’archipel de la Manche",
  "lart-detre-grand-pere.txt": "L’art D’être Grand-père",
  "lavarice-et-lenvie.txt": "L’avarice et L’envie",
  "le-4-novembre-1820-saint-charles.txt": "Le 4 Novembre 1820 – Saint-charles",
  "le-dernier-jour-dun-condamne.txt": "Le Dernier Jour D’un Condamné",
  "le-pape.txt": "Le Pape",
  "le-retour-de-lempereur.txt": "Le Retour de L’empereur",
  "le-rhin-1-lettres-a-un-ami.txt": "Le Rhin 1 Lettres à un Ami",
  "le-rhin-2-lettres-a-un-ami.txt": "Le Rhin 2 Lettres à un Ami",
  "le-rhin-3-lettres-a-un-ami.txt": "Le Rhin 3 Lettres à un Ami",
  "le-roi-samuse.txt": "Le Roi S’amuse",
  "le-suffrage-universel.txt": "Le Suffrage Universel",
  "le-telegraphe.txt": "Le Télégraphe",
  "le-vieillard-du-galese.txt": "Le Vieillard du Galèse",
  "lenroleur-politique.txt": "L’enrôleur Politique",
  "lepee.txt": "L’épée",
  "les-annees-funestes.txt": "Les Années Funestes",
  "les-burgraves.txt": "Les Burgraves",
  "les-chansons-des-rues-et-des-bois.txt": "Les Chansons des Rues et des Bois",
  "les-chants-du-crepuscule.txt": "Les Chants du Crépuscule",
  "les-chatiments.txt": "Les Châtiments",
  "les-contemplations.txt": "Les Contemplations",
  "les-derniers-bardes.txt": "Les Derniers Bardes",
  "les-deux-trouvailles-de-gallus.txt": "Les Deux Trouvailles de Gallus",
  "les-enfants-le-livre-des-meres.txt": "Les Enfants le Livre des Mères",
  "les-feuilles-dautomne.txt": "Les Feuilles D’automne",
  "les-gueux.txt": "Les Gueux",
  "les-jumeaux.txt": "Les Jumeaux",
  "les-miserables--tome-1-fantine.txt": "Les Misérables",
  "les-miserables--tome-2-cosette.txt": "Les Misérables",
  "les-miserables--tome-3-marius.txt": "Les Misérables",
  "les-miserables--tome-4-lidylle-rue-plumet.txt": "Les Misérables",
  "les-miserables--tome-5-jean-valjean.txt": "Les Misérables",
  "les-miserables.txt": "Les Misérables",
  "les-orientales.txt": "Les Orientales",
  "les-premieres-publications.txt": "Les Premières Publications",
  "les-quatre-vents-de-lesprit.txt": "Les Quatre Vents de L’esprit",
  "les-rayons-et-les-ombres.txt": "Les Rayons et les Ombres",
  "les-travailleurs-de-la-mer.txt": "Les Travailleurs de la Mer",
  "les-voix-interieures.txt": "Les Voix Intérieures",
  "lettres-a-la-fiancee.txt": "Lettres a la Fiancée",
  "lhomme-qui-rit.txt": "L’homme qui Rit",
  "litterature-et-philosophie-melees.txt": "Littérature et Philosophie Mêlées",
  "lucrece-borgia.txt": "Lucrèce Borgia",
  "mandats-politiques-de-victor-hugo.txt": "Mandats Politiques de Victor Hugo",
  "mangeront-ils.txt": "Mangeront-ils ?",
  "marie-tudor.txt": "Marie Tudor",
  "marion-delorme.txt": "Marion Delorme",
  "mes-fils.txt": "Mes Fils",
  "mille-francs-de-recompense.txt": "Mille Francs de Récompense",
  "napoleon-le-petit.txt": "Napoléon le Petit",
  "note-de-lediteur.txt": "Note de L’éditeur",
  "notre-dame-de-paris.txt": "Notre Dame de Paris",
  "odes-et-ballades.txt": "Odes et Ballades",
  "paris.txt": "Paris",
  "poesies-diverses.txt": "Poésies Diverses",
  "post-scriptum-de-ma-vie.txt": "Post-scriptum de Ma Vie",
  "preface-de-la-nouvelle-traduction-de-shakespeare.txt": "Préface de la Nouvelle Traduction de Shakespeare",
  "presentation.txt": "Présentation",
  "prologue.txt": "Prologue",
  "quatre-vingt-treize.txt": "Quatre-vingt-treize",
  "raymond-dascoli.txt": "Raymond D’ascoli",
  "religions-et-religion.txt": "Religions et Religion",
  "ruy-blas.txt": "Ruy Blas",
  "sur-la-lisiere-dun-bois.txt": "Sur la Lisière D’un Bois",
  "theatre-en-liberte.txt": "Théâtre en Liberté",
  "torquemada.txt": "Torquemada",
  "toute-la-lyre.txt": "Toute la Lyre",
  "william-shakespeare.txt": "William Shakespeare",
}

export default HUGO_TITLES
