const ZOLA_TITLES: Record<string, string> = {
  "a-mes-amis.txt": "À Mes Amis",
  "a-mon-ami-paul.txt": "À Mon Ami Paul",
  "a-mon-dernier-amour.txt": "À Mon Dernier Amour",
  "angeline-ou-la-maison-hantee--chapitre-01.txt":
    "Angeline ou la Maison Hantée",
  "angeline-ou-la-maison-hantee--chapitre-02.txt":
    "Angeline ou la Maison Hantée",
  "angeline-ou-la-maison-hantee--chapitre-03.txt":
    "Angeline ou la Maison Hantée",
  "angeline-ou-la-maison-hantee.txt": "Angeline ou la Maison Hantée",
  "au-bonheur-des-dames--chapitre-01.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-02.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-03.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-04.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-05.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-06.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-07.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-08.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-09.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-10.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-11.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-12.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-13.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames--chapitre-14.txt": "Au Bonheur des Dames",
  "au-bonheur-des-dames.txt": "Au Bonheur des Dames",
  "biographie-panoramique.txt": "Biographie Panoramique",
  "ce-que-je-veux.txt": "Ce que Je Veux",
  "citations-les-plus-celebres.txt": "Citations les Plus Célèbres",
  "comment-on-meurt--chapitre-01.txt": "Comment On Meurt",
  "comment-on-meurt--chapitre-02.txt": "Comment On Meurt",
  "comment-on-meurt--chapitre-03.txt": "Comment On Meurt",
  "comment-on-meurt--chapitre-04.txt": "Comment On Meurt",
  "comment-on-meurt--chapitre-05.txt": "Comment On Meurt",
  "comment-on-meurt.txt": "Comment On Meurt",
  "contes-a-ninon--chapitre-01.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-02.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-03.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-04.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-05.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-06.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-07.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-08.txt": "Contes a Ninon",
  "contes-a-ninon--chapitre-09.txt": "Contes a Ninon",
  "contes-a-ninon.txt": "Contes a Ninon",
  "de-la-critique--chapitre-01.txt": "De la Critique",
  "de-la-critique--chapitre-02.txt": "De la Critique",
  "de-la-critique--chapitre-03.txt": "De la Critique",
  "de-la-critique--chapitre-04.txt": "De la Critique",
  "de-la-critique--chapitre-05.txt": "De la Critique",
  "de-la-critique--chapitre-06.txt": "De la Critique",
  "de-la-critique--chapitre-07.txt": "De la Critique",
  "de-la-critique--chapitre-08.txt": "De la Critique",
  "de-la-critique--chapitre-09.txt": "De la Critique",
  "de-la-critique.txt": "De la Critique",
  "de-la-moralite.txt": "De la Moralité",
  "discours-dinauguration-du-buste-demmanuel-gonzales.txt":
    "Discours D’inauguration du Buste D’emmanuel Gonzales",
  "discours-dinauguration-du-monument-de-guy-de-maupassant-au-parc-monceau.txt":
    "Discours D’inauguration du Monument de Guy de Maupassant au Parc Monceau",
  "documents-litteraires--chapitre-01.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-02.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-03.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-04.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-05.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-06.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-07.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-08.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-09.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-10.txt": "Documents Littéraires",
  "documents-litteraires--chapitre-11.txt": "Documents Littéraires",
  "documents-litteraires.txt": "Documents Littéraires",
  "du-roman--chapitre-01.txt": "Du Roman",
  "du-roman--chapitre-02.txt": "Du Roman",
  "du-roman--chapitre-03.txt": "Du Roman",
  "du-roman--chapitre-04.txt": "Du Roman",
  "du-roman--chapitre-05.txt": "Du Roman",
  "du-roman--chapitre-06.txt": "Du Roman",
  "du-roman--chapitre-07.txt": "Du Roman",
  "du-roman.txt": "Du Roman",
  "edouard-manet--chapitre-01.txt": "Édouard Manet",
  "edouard-manet--chapitre-02.txt": "Édouard Manet",
  "edouard-manet--chapitre-03.txt": "Édouard Manet",
  "edouard-manet--chapitre-04.txt": "Édouard Manet",
  "edouard-manet.txt": "Édouard Manet",
  "eloge-obseques-dalphonse-daudet.txt": "Éloge : Obsèques D’alphonse Daudet",
  "eloge-obseques-darsene-houssaye.txt": "Éloge : Obsèques D’arsène Houssaye",
  "eloge-obseques-de-guy-de-maupassant.txt":
    "Éloge : Obsèques de Guy de Maupassant",
  "eloge-obseques-de-leon-cladel.txt": "Éloge : Obsèques de Léon Cladel",
  "eloge-obseques-de-paul-alexis.txt": "Éloge : Obsèques de Paul Alexis",
  "eloge-obseques-dedmond-de-goncourt.txt":
    "Éloge : Obsèques D’edmond de Goncourt",
  "emile-zola-notes-dun-ami--chapitre-01.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-02.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-03.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-04.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-05.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-06.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-07.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-08.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-09.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-10.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-11.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami--chapitre-12.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-notes-dun-ami.txt": "Émile Zola – Notes D’un Ami",
  "emile-zola-sa-vie-son-oeuvre--chapitre-01.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-02.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-03.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-04.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-05.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-06.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-07.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-08.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-09.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre--chapitre-10.txt":
    "Émile Zola : Sa Vie – Son Oeuvre",
  "emile-zola-sa-vie-son-oeuvre.txt": "Émile Zola : Sa Vie – Son Oeuvre",
  "esquisses-parisiennes--chapitre-01.txt": "Esquisses Parisiennes",
  "esquisses-parisiennes--chapitre-02.txt": "Esquisses Parisiennes",
  "esquisses-parisiennes--chapitre-03.txt": "Esquisses Parisiennes",
  "esquisses-parisiennes--chapitre-04.txt": "Esquisses Parisiennes",
  "esquisses-parisiennes.txt": "Esquisses Parisiennes",
  "germinal--chapitre-01.txt": "Germinal",
  "germinal--chapitre-02.txt": "Germinal",
  "germinal--chapitre-03.txt": "Germinal",
  "germinal--chapitre-04.txt": "Germinal",
  "germinal--chapitre-05.txt": "Germinal",
  "germinal--chapitre-06.txt": "Germinal",
  "germinal--chapitre-07.txt": "Germinal",
  "germinal.txt": "Germinal",
  "jaccuse.txt": "J’accuse… !",
  "jacques-damour--chapitre-01.txt": "Jacques Damour",
  "jacques-damour--chapitre-02.txt": "Jacques Damour",
  "jacques-damour--chapitre-03.txt": "Jacques Damour",
  "jacques-damour--chapitre-04.txt": "Jacques Damour",
  "jacques-damour.txt": "Jacques Damour",
  "la-banlieue--chapitre-01.txt": "La Banlieue",
  "la-banlieue--chapitre-02.txt": "La Banlieue",
  "la-banlieue--chapitre-03.txt": "La Banlieue",
  "la-banlieue--chapitre-04.txt": "La Banlieue",
  "la-banlieue--chapitre-05.txt": "La Banlieue",
  "la-banlieue.txt": "La Banlieue",
  "la-bete-humaine--chapitre-01.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-02.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-03.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-04.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-05.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-06.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-07.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-08.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-09.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-10.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-11.txt": "La Bête Humaine",
  "la-bete-humaine--chapitre-12.txt": "La Bête Humaine",
  "la-bete-humaine.txt": "La Bête Humaine",
  "la-confession-de-claude--chapitre-01.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-02.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-03.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-04.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-05.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-06.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-07.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-08.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-09.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-10.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-11.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-12.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-13.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-14.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-15.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-16.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-17.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-18.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-19.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-20.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-21.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-22.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-23.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-24.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-25.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-26.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-27.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-28.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-29.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-30.txt": "La Confession de Claude",
  "la-confession-de-claude--chapitre-31.txt": "La Confession de Claude",
  "la-confession-de-claude.txt": "La Confession de Claude",
  "la-conquete-de-plassans--chapitre-01.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-02.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-03.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-04.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-05.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-06.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-07.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-08.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-09.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-10.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-11.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-12.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-13.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-14.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-15.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-16.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-17.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-18.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-19.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-20.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-21.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-22.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans--chapitre-23.txt": "La Conquête de Plassans",
  "la-conquete-de-plassans.txt": "La Conquête de Plassans",
  "la-curee--chapitre-01.txt": "La Curée",
  "la-curee--chapitre-02.txt": "La Curée",
  "la-curee--chapitre-03.txt": "La Curée",
  "la-curee--chapitre-04.txt": "La Curée",
  "la-curee--chapitre-05.txt": "La Curée",
  "la-curee--chapitre-06.txt": "La Curée",
  "la-curee--chapitre-07.txt": "La Curée",
  "la-curee.txt": "La Curée",
  "la-debacle--chapitre-01.txt": "La Débâcle",
  "la-debacle--chapitre-02.txt": "La Débâcle",
  "la-debacle--chapitre-03.txt": "La Débâcle",
  "la-debacle.txt": "La Débâcle",
  "la-faute-de-labbe-mouret--chapitre-01.txt": "La Faute de l'Abbé Mouret",
  "la-faute-de-labbe-mouret--chapitre-02.txt": "La Faute de l'Abbé Mouret",
  "la-faute-de-labbe-mouret--chapitre-03.txt": "La Faute de l'Abbé Mouret",
  "la-faute-de-labbe-mouret.txt": "La Faute de l'Abbé Mouret",
  "la-fete-a-coqueville--chapitre-01.txt": "La Fête à Coqueville",
  "la-fete-a-coqueville--chapitre-02.txt": "La Fête à Coqueville",
  "la-fete-a-coqueville--chapitre-03.txt": "La Fête à Coqueville",
  "la-fete-a-coqueville--chapitre-04.txt": "La Fête à Coqueville",
  "la-fete-a-coqueville--chapitre-05.txt": "La Fête à Coqueville",
  "la-fete-a-coqueville--chapitre-06.txt": "La Fête à Coqueville",
  "la-fete-a-coqueville.txt": "La Fête à Coqueville",
  "la-fortune-des-rougon--chapitre-01.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon--chapitre-02.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon--chapitre-03.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon--chapitre-04.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon--chapitre-05.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon--chapitre-06.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon--chapitre-07.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon--chapitre-08.txt": "La Fortune des Rougon",
  "la-fortune-des-rougon.txt": "La Fortune des Rougon",
  "la-joie-de-vivre--chapitre-01.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-02.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-03.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-04.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-05.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-06.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-07.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-08.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-09.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-10.txt": "La Joie de Vivre",
  "la-joie-de-vivre--chapitre-11.txt": "La Joie de Vivre",
  "la-joie-de-vivre.txt": "La Joie de Vivre",
  "la-mort-dolivier-becaille--chapitre-01.txt": "La Mort D’olivier Bécaille",
  "la-mort-dolivier-becaille--chapitre-02.txt": "La Mort D’olivier Bécaille",
  "la-mort-dolivier-becaille--chapitre-03.txt": "La Mort D’olivier Bécaille",
  "la-mort-dolivier-becaille--chapitre-04.txt": "La Mort D’olivier Bécaille",
  "la-mort-dolivier-becaille--chapitre-05.txt": "La Mort D’olivier Bécaille",
  "la-mort-dolivier-becaille--chapitre-06.txt": "La Mort D’olivier Bécaille",
  "la-mort-dolivier-becaille.txt": "La Mort D’olivier Bécaille",
  "la-republique-et-la-litterature--chapitre-01.txt":
    "La République et la Littérature",
  "la-republique-et-la-litterature--chapitre-02.txt":
    "La République et la Littérature",
  "la-republique-et-la-litterature--chapitre-03.txt":
    "La République et la Littérature",
  "la-republique-et-la-litterature.txt": "La République et la Littérature",
  "la-riviere--chapitre-01.txt": "La Rivière",
  "la-riviere--chapitre-02.txt": "La Rivière",
  "la-riviere--chapitre-03.txt": "La Rivière",
  "la-riviere--chapitre-04.txt": "La Rivière",
  "la-riviere--chapitre-05.txt": "La Rivière",
  "la-riviere--chapitre-06.txt": "La Rivière",
  "la-riviere.txt": "La Rivière",
  "la-terre--chapitre-01.txt": "La Terre",
  "la-terre--chapitre-02.txt": "La Terre",
  "la-terre--chapitre-03.txt": "La Terre",
  "la-terre--chapitre-04.txt": "La Terre",
  "la-terre--chapitre-05.txt": "La Terre",
  "la-terre.txt": "La Terre",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-01.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-02.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-03.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-04.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-05.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-06.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-07.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-08.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-09.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-10.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-11.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-12.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-13.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-14.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-15.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-16.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-17.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus--chapitre-18.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "la-verite-en-marche-laffaire-dreyfus.txt":
    "La Vérité en Marche (l’affaire Dreyfus)",
  "lamoureuse-comedie--chapitre-01.txt": "L'Amoureuse Comédie",
  "lamoureuse-comedie--chapitre-02.txt": "L'Amoureuse Comédie",
  "lamoureuse-comedie--chapitre-03.txt": "L'Amoureuse Comédie",
  "lamoureuse-comedie--chapitre-04.txt": "L'Amoureuse Comédie",
  "lamoureuse-comedie.txt": "L'Amoureuse Comédie",
  "largent--chapitre-01.txt": "L'Argent",
  "largent--chapitre-02.txt": "L'Argent",
  "largent--chapitre-03.txt": "L'Argent",
  "largent--chapitre-04.txt": "L'Argent",
  "largent--chapitre-05.txt": "L'Argent",
  "largent--chapitre-06.txt": "L'Argent",
  "largent--chapitre-07.txt": "L'Argent",
  "largent--chapitre-08.txt": "L'Argent",
  "largent--chapitre-09.txt": "L'Argent",
  "largent--chapitre-10.txt": "L'Argent",
  "largent--chapitre-11.txt": "L'Argent",
  "largent--chapitre-12.txt": "L'Argent",
  "largent-dans-la-litterature--chapitre-01.txt":
    "L’argent dans la Littérature",
  "largent-dans-la-litterature--chapitre-02.txt":
    "L’argent dans la Littérature",
  "largent-dans-la-litterature--chapitre-03.txt":
    "L’argent dans la Littérature",
  "largent-dans-la-litterature--chapitre-04.txt":
    "L’argent dans la Littérature",
  "largent-dans-la-litterature--chapitre-05.txt":
    "L’argent dans la Littérature",
  "largent-dans-la-litterature--chapitre-06.txt":
    "L’argent dans la Littérature",
  "largent-dans-la-litterature.txt": "L’argent dans la Littérature",
  "largent.txt": "L'Argent",
  "lassommoir--chapitre-01.txt": "L'Assommoir",
  "lassommoir--chapitre-02.txt": "L'Assommoir",
  "lassommoir--chapitre-03.txt": "L'Assommoir",
  "lassommoir--chapitre-04.txt": "L'Assommoir",
  "lassommoir--chapitre-05.txt": "L'Assommoir",
  "lassommoir--chapitre-06.txt": "L'Assommoir",
  "lassommoir--chapitre-07.txt": "L'Assommoir",
  "lassommoir--chapitre-08.txt": "L'Assommoir",
  "lassommoir--chapitre-09.txt": "L'Assommoir",
  "lassommoir--chapitre-10.txt": "L'Assommoir",
  "lassommoir--chapitre-11.txt": "L'Assommoir",
  "lassommoir--chapitre-12.txt": "L'Assommoir",
  "lassommoir--chapitre-13.txt": "L'Assommoir",
  "lassommoir--chapitre-14.txt": "L'Assommoir",
  "lassommoir.txt": "L'Assommoir",
  "lattaque-du-moulin--chapitre-01.txt": "L’attaque du Moulin",
  "lattaque-du-moulin--chapitre-02.txt": "L’attaque du Moulin",
  "lattaque-du-moulin--chapitre-03.txt": "L’attaque du Moulin",
  "lattaque-du-moulin--chapitre-04.txt": "L’attaque du Moulin",
  "lattaque-du-moulin--chapitre-05.txt": "L’attaque du Moulin",
  "lattaque-du-moulin.txt": "L’attaque du Moulin",
  "le-bois--chapitre-01.txt": "Le Bois",
  "le-bois--chapitre-02.txt": "Le Bois",
  "le-bois--chapitre-03.txt": "Le Bois",
  "le-bois--chapitre-04.txt": "Le Bois",
  "le-bois--chapitre-05.txt": "Le Bois",
  "le-bois.txt": "Le Bois",
  "le-bouton-de-rose--chapitre-01.txt": "Le Bouton de Rose",
  "le-bouton-de-rose--chapitre-02.txt": "Le Bouton de Rose",
  "le-bouton-de-rose--chapitre-03.txt": "Le Bouton de Rose",
  "le-bouton-de-rose--chapitre-04.txt": "Le Bouton de Rose",
  "le-bouton-de-rose--chapitre-05.txt": "Le Bouton de Rose",
  "le-bouton-de-rose.txt": "Le Bouton de Rose",
  "le-capitaine-burle--chapitre-01.txt": "Le Capitaine Burle",
  "le-capitaine-burle--chapitre-02.txt": "Le Capitaine Burle",
  "le-capitaine-burle--chapitre-03.txt": "Le Capitaine Burle",
  "le-capitaine-burle--chapitre-04.txt": "Le Capitaine Burle",
  "le-capitaine-burle.txt": "Le Capitaine Burle",
  "le-diable-ermite.txt": "Le Diable Ermite",
  "le-docteur-pascal--chapitre-01.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-02.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-03.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-04.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-05.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-06.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-07.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-08.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-09.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-10.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-11.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-12.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-13.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-14.txt": "Le Docteur Pascal",
  "le-docteur-pascal--chapitre-15.txt": "Le Docteur Pascal",
  "le-docteur-pascal.txt": "Le Docteur Pascal",
  "le-naturalisme-au-theatre--chapitre-01.txt": "Le Naturalisme au Théâtre",
  "le-naturalisme-au-theatre--chapitre-02.txt": "Le Naturalisme au Théâtre",
  "le-naturalisme-au-theatre--chapitre-03.txt": "Le Naturalisme au Théâtre",
  "le-naturalisme-au-theatre.txt": "Le Naturalisme au Théâtre",
  "le-reve--chapitre-01.txt": "Le Rêve",
  "le-reve--chapitre-02.txt": "Le Rêve",
  "le-reve--chapitre-03.txt": "Le Rêve",
  "le-reve--chapitre-04.txt": "Le Rêve",
  "le-reve--chapitre-05.txt": "Le Rêve",
  "le-reve--chapitre-06.txt": "Le Rêve",
  "le-reve--chapitre-07.txt": "Le Rêve",
  "le-reve--chapitre-08.txt": "Le Rêve",
  "le-reve--chapitre-09.txt": "Le Rêve",
  "le-reve--chapitre-10.txt": "Le Rêve",
  "le-reve--chapitre-11.txt": "Le Rêve",
  "le-reve--chapitre-12.txt": "Le Rêve",
  "le-reve--chapitre-13.txt": "Le Rêve",
  "le-reve--chapitre-14.txt": "Le Rêve",
  "le-reve.txt": "Le Rêve",
  "le-roman-experimental--chapitre-01.txt": "Le Roman Expérimental",
  "le-roman-experimental--chapitre-02.txt": "Le Roman Expérimental",
  "le-roman-experimental--chapitre-03.txt": "Le Roman Expérimental",
  "le-roman-experimental--chapitre-04.txt": "Le Roman Expérimental",
  "le-roman-experimental--chapitre-05.txt": "Le Roman Expérimental",
  "le-roman-experimental--chapitre-06.txt": "Le Roman Expérimental",
  "le-roman-experimental.txt": "Le Roman Expérimental",
  "le-ventre-de-paris--chapitre-01.txt": "Le Ventre de Paris",
  "le-ventre-de-paris--chapitre-02.txt": "Le Ventre de Paris",
  "le-ventre-de-paris--chapitre-03.txt": "Le Ventre de Paris",
  "le-ventre-de-paris--chapitre-04.txt": "Le Ventre de Paris",
  "le-ventre-de-paris--chapitre-05.txt": "Le Ventre de Paris",
  "le-ventre-de-paris--chapitre-06.txt": "Le Ventre de Paris",
  "le-ventre-de-paris.txt": "Le Ventre de Paris",
  "le-voeu-dune-morte--chapitre-01.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-02.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-03.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-04.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-05.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-06.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-07.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-08.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-09.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-10.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-11.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-12.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-13.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-14.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-15.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte--chapitre-16.txt": "Le Voeu D’une Morte",
  "le-voeu-dune-morte.txt": "Le Voeu D’une Morte",
  "les-coquillages-de-m-chabre--chapitre-01.txt":
    "Les Coquillages de M. Chabre",
  "les-coquillages-de-m-chabre--chapitre-02.txt":
    "Les Coquillages de M. Chabre",
  "les-coquillages-de-m-chabre--chapitre-03.txt":
    "Les Coquillages de M. Chabre",
  "les-coquillages-de-m-chabre--chapitre-04.txt":
    "Les Coquillages de M. Chabre",
  "les-coquillages-de-m-chabre--chapitre-05.txt":
    "Les Coquillages de M. Chabre",
  "les-coquillages-de-m-chabre--chapitre-06.txt":
    "Les Coquillages de M. Chabre",
  "les-coquillages-de-m-chabre.txt": "Les Coquillages de M. Chabre",
  "les-heritiers-rabourdin--chapitre-01.txt": "Les Héritiers Rabourdin",
  "les-heritiers-rabourdin--chapitre-02.txt": "Les Héritiers Rabourdin",
  "les-heritiers-rabourdin--chapitre-03.txt": "Les Héritiers Rabourdin",
  "les-heritiers-rabourdin--chapitre-04.txt": "Les Héritiers Rabourdin",
  "les-heritiers-rabourdin--chapitre-05.txt": "Les Héritiers Rabourdin",
  "les-heritiers-rabourdin.txt": "Les Héritiers Rabourdin",
  "les-lettres-et-les-arts--chapitre-01.txt": "Les Lettres et les Arts",
  "les-lettres-et-les-arts--chapitre-02.txt": "Les Lettres et les Arts",
  "les-lettres-et-les-arts--chapitre-03.txt": "Les Lettres et les Arts",
  "les-lettres-et-les-arts.txt": "Les Lettres et les Arts",
  "les-mysteres-de-marseille--chapitre-01.txt": "Les Mystères de Marseille",
  "les-mysteres-de-marseille--chapitre-02.txt": "Les Mystères de Marseille",
  "les-mysteres-de-marseille--chapitre-03.txt": "Les Mystères de Marseille",
  "les-mysteres-de-marseille--chapitre-04.txt": "Les Mystères de Marseille",
  "les-mysteres-de-marseille.txt": "Les Mystères de Marseille",
  "les-quatre-evangiles-fecondite--chapitre-01.txt":
    "Les Quatre Évangiles : Fécondité",
  "les-quatre-evangiles-fecondite--chapitre-02.txt":
    "Les Quatre Évangiles : Fécondité",
  "les-quatre-evangiles-fecondite--chapitre-03.txt":
    "Les Quatre Évangiles : Fécondité",
  "les-quatre-evangiles-fecondite--chapitre-04.txt":
    "Les Quatre Évangiles : Fécondité",
  "les-quatre-evangiles-fecondite--chapitre-05.txt":
    "Les Quatre Évangiles : Fécondité",
  "les-quatre-evangiles-fecondite--chapitre-06.txt":
    "Les Quatre Évangiles : Fécondité",
  "les-quatre-evangiles-fecondite.txt": "Les Quatre Évangiles : Fécondité",
  "les-quatre-evangiles-travail--chapitre-01.txt":
    "Les Quatre Évangiles : Travail",
  "les-quatre-evangiles-travail--chapitre-02.txt":
    "Les Quatre Évangiles : Travail",
  "les-quatre-evangiles-travail--chapitre-03.txt":
    "Les Quatre Évangiles : Travail",
  "les-quatre-evangiles-travail.txt": "Les Quatre Évangiles : Travail",
  "les-quatre-evangiles-verite--chapitre-01.txt":
    "Les Quatre Évangiles : Vérité",
  "les-quatre-evangiles-verite--chapitre-02.txt":
    "Les Quatre Évangiles : Vérité",
  "les-quatre-evangiles-verite--chapitre-03.txt":
    "Les Quatre Évangiles : Vérité",
  "les-quatre-evangiles-verite--chapitre-04.txt":
    "Les Quatre Évangiles : Vérité",
  "les-quatre-evangiles-verite.txt": "Les Quatre Évangiles : Vérité",
  "les-romanciers-contemporains--chapitre-01.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains--chapitre-02.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains--chapitre-03.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains--chapitre-04.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains--chapitre-05.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains--chapitre-06.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains--chapitre-07.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains--chapitre-08.txt":
    "Les Romanciers Contemporains",
  "les-romanciers-contemporains.txt": "Les Romanciers Contemporains",
  "les-romanciers-naturalistes--chapitre-01.txt": "Les Romanciers Naturalistes",
  "les-romanciers-naturalistes--chapitre-02.txt": "Les Romanciers Naturalistes",
  "les-romanciers-naturalistes--chapitre-03.txt": "Les Romanciers Naturalistes",
  "les-romanciers-naturalistes--chapitre-04.txt": "Les Romanciers Naturalistes",
  "les-romanciers-naturalistes--chapitre-05.txt": "Les Romanciers Naturalistes",
  "les-romanciers-naturalistes--chapitre-06.txt": "Les Romanciers Naturalistes",
  "les-romanciers-naturalistes.txt": "Les Romanciers Naturalistes",
  "les-trois-villes-lourdes--chapitre-01.txt": "Les Trois Villes : Lourdes",
  "les-trois-villes-lourdes--chapitre-02.txt": "Les Trois Villes : Lourdes",
  "les-trois-villes-lourdes--chapitre-03.txt": "Les Trois Villes : Lourdes",
  "les-trois-villes-lourdes--chapitre-04.txt": "Les Trois Villes : Lourdes",
  "les-trois-villes-lourdes--chapitre-05.txt": "Les Trois Villes : Lourdes",
  "les-trois-villes-lourdes.txt": "Les Trois Villes : Lourdes",
  "les-trois-villes-paris--chapitre-01.txt": "Les Trois Villes : Paris",
  "les-trois-villes-paris--chapitre-02.txt": "Les Trois Villes : Paris",
  "les-trois-villes-paris--chapitre-03.txt": "Les Trois Villes : Paris",
  "les-trois-villes-paris--chapitre-04.txt": "Les Trois Villes : Paris",
  "les-trois-villes-paris--chapitre-05.txt": "Les Trois Villes : Paris",
  "les-trois-villes-paris.txt": "Les Trois Villes : Paris",
  "les-trois-villes-rome--chapitre-01.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-02.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-03.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-04.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-05.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-06.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-07.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-08.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-09.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-10.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-11.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-12.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-13.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-14.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-15.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome--chapitre-16.txt": "Les Trois Villes : Rome",
  "les-trois-villes-rome.txt": "Les Trois Villes : Rome",
  "lettre-a-la-jeunesse--chapitre-01.txt": "Lettre à la Jeunesse",
  "lettre-a-la-jeunesse--chapitre-02.txt": "Lettre à la Jeunesse",
  "lettre-a-la-jeunesse--chapitre-03.txt": "Lettre à la Jeunesse",
  "lettre-a-la-jeunesse--chapitre-04.txt": "Lettre à la Jeunesse",
  "lettre-a-la-jeunesse--chapitre-05.txt": "Lettre à la Jeunesse",
  "lettre-a-la-jeunesse--chapitre-06.txt": "Lettre à la Jeunesse",
  "lettre-a-la-jeunesse.txt": "Lettre à la Jeunesse",
  "lettres-de-jeunesse--chapitre-01.txt": "Lettres de Jeunesse",
  "lettres-de-jeunesse--chapitre-02.txt": "Lettres de Jeunesse",
  "lettres-de-jeunesse--chapitre-03.txt": "Lettres de Jeunesse",
  "lettres-de-jeunesse.txt": "Lettres de Jeunesse",
  "linondation--chapitre-01.txt": "L’inondation",
  "linondation--chapitre-02.txt": "L’inondation",
  "linondation--chapitre-03.txt": "L’inondation",
  "linondation--chapitre-04.txt": "L’inondation",
  "linondation--chapitre-05.txt": "L’inondation",
  "linondation--chapitre-06.txt": "L’inondation",
  "linondation--chapitre-07.txt": "L’inondation",
  "linondation.txt": "L’inondation",
  "loeuvre--chapitre-01.txt": "L'Oeuvre",
  "loeuvre--chapitre-02.txt": "L'Oeuvre",
  "loeuvre--chapitre-03.txt": "L'Oeuvre",
  "loeuvre--chapitre-04.txt": "L'Oeuvre",
  "loeuvre--chapitre-05.txt": "L'Oeuvre",
  "loeuvre--chapitre-06.txt": "L'Oeuvre",
  "loeuvre--chapitre-07.txt": "L'Oeuvre",
  "loeuvre--chapitre-08.txt": "L'Oeuvre",
  "loeuvre--chapitre-09.txt": "L'Oeuvre",
  "loeuvre--chapitre-10.txt": "L'Oeuvre",
  "loeuvre--chapitre-11.txt": "L'Oeuvre",
  "loeuvre--chapitre-12.txt": "L'Oeuvre",
  "loeuvre.txt": "L'Oeuvre",
  "madame-neigeon--chapitre-01.txt": "Madame Neigeon",
  "madame-neigeon--chapitre-02.txt": "Madame Neigeon",
  "madame-neigeon--chapitre-03.txt": "Madame Neigeon",
  "madame-neigeon--chapitre-04.txt": "Madame Neigeon",
  "madame-neigeon--chapitre-05.txt": "Madame Neigeon",
  "madame-neigeon.txt": "Madame Neigeon",
  "madame-sourdis--chapitre-01.txt": "Madame Sourdis",
  "madame-sourdis--chapitre-02.txt": "Madame Sourdis",
  "madame-sourdis--chapitre-03.txt": "Madame Sourdis",
  "madame-sourdis--chapitre-04.txt": "Madame Sourdis",
  "madame-sourdis--chapitre-05.txt": "Madame Sourdis",
  "madame-sourdis.txt": "Madame Sourdis",
  "madeleine-ferat--chapitre-01.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-02.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-03.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-04.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-05.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-06.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-07.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-08.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-09.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-10.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-11.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-12.txt": "Madeleine Férat",
  "madeleine-ferat--chapitre-13.txt": "Madeleine Férat",
  "madeleine-ferat.txt": "Madeleine Férat",
  "mes-haines--chapitre-01.txt": "Mes Haines",
  "mes-haines--chapitre-02.txt": "Mes Haines",
  "mes-haines--chapitre-03.txt": "Mes Haines",
  "mes-haines--chapitre-04.txt": "Mes Haines",
  "mes-haines--chapitre-05.txt": "Mes Haines",
  "mes-haines--chapitre-06.txt": "Mes Haines",
  "mes-haines--chapitre-07.txt": "Mes Haines",
  "mes-haines--chapitre-08.txt": "Mes Haines",
  "mes-haines--chapitre-09.txt": "Mes Haines",
  "mes-haines--chapitre-10.txt": "Mes Haines",
  "mes-haines--chapitre-11.txt": "Mes Haines",
  "mes-haines--chapitre-12.txt": "Mes Haines",
  "mes-haines--chapitre-13.txt": "Mes Haines",
  "mes-haines--chapitre-14.txt": "Mes Haines",
  "mes-haines--chapitre-15.txt": "Mes Haines",
  "mes-haines--chapitre-16.txt": "Mes Haines",
  "mes-haines--chapitre-17.txt": "Mes Haines",
  "mes-haines.txt": "Mes Haines",
  "messidor--chapitre-01.txt": "Messidor",
  "messidor--chapitre-02.txt": "Messidor",
  "messidor--chapitre-03.txt": "Messidor",
  "messidor--chapitre-04.txt": "Messidor",
  "messidor--chapitre-05.txt": "Messidor",
  "messidor.txt": "Messidor",
  "mon-salon--chapitre-01.txt": "Mon Salon",
  "mon-salon--chapitre-02.txt": "Mon Salon",
  "mon-salon--chapitre-03.txt": "Mon Salon",
  "mon-salon--chapitre-04.txt": "Mon Salon",
  "mon-salon--chapitre-05.txt": "Mon Salon",
  "mon-salon--chapitre-06.txt": "Mon Salon",
  "mon-salon--chapitre-07.txt": "Mon Salon",
  "mon-salon--chapitre-08.txt": "Mon Salon",
  "mon-salon--chapitre-09.txt": "Mon Salon",
  "mon-salon--chapitre-10.txt": "Mon Salon",
  "mon-salon.txt": "Mon Salon",
  "nais-micoulin--chapitre-01.txt": "Naïs Micoulin",
  "nais-micoulin--chapitre-02.txt": "Naïs Micoulin",
  "nais-micoulin--chapitre-03.txt": "Naïs Micoulin",
  "nais-micoulin--chapitre-04.txt": "Naïs Micoulin",
  "nais-micoulin--chapitre-05.txt": "Naïs Micoulin",
  "nais-micoulin--chapitre-06.txt": "Naïs Micoulin",
  "nais-micoulin.txt": "Naïs Micoulin",
  "nana--chapitre-01.txt": "Nana",
  "nana--chapitre-02.txt": "Nana",
  "nana--chapitre-03.txt": "Nana",
  "nana--chapitre-04.txt": "Nana",
  "nana--chapitre-05.txt": "Nana",
  "nana--chapitre-06.txt": "Nana",
  "nana--chapitre-07.txt": "Nana",
  "nana--chapitre-08.txt": "Nana",
  "nana--chapitre-09.txt": "Nana",
  "nana--chapitre-10.txt": "Nana",
  "nana--chapitre-11.txt": "Nana",
  "nana--chapitre-12.txt": "Nana",
  "nana--chapitre-13.txt": "Nana",
  "nana--chapitre-14.txt": "Nana",
  "nana.txt": "Nana",
  "nantas--chapitre-01.txt": "Nantas",
  "nantas--chapitre-02.txt": "Nantas",
  "nantas--chapitre-03.txt": "Nantas",
  "nantas--chapitre-04.txt": "Nantas",
  "nantas--chapitre-05.txt": "Nantas",
  "nantas--chapitre-06.txt": "Nantas",
  "nantas.txt": "Nantas",
  "nina.txt": "Nina",
  "nos-auteurs-dramatiques--chapitre-01.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-02.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-03.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-04.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-05.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-06.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-07.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-08.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-09.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-10.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-11.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-12.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-13.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-14.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-15.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-16.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques--chapitre-17.txt": "Nos Auteurs Dramatiques",
  "nos-auteurs-dramatiques.txt": "Nos Auteurs Dramatiques",
  "note-de-lediteur.txt": "Note de L’éditeur",
  "nouveaux-contes-a-ninon--chapitre-01.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-02.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-03.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-04.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-05.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-06.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-07.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-08.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-09.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-10.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-11.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-12.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon--chapitre-13.txt": "Nouveaux Contes a Ninon",
  "nouveaux-contes-a-ninon.txt": "Nouveaux Contes a Ninon",
  "nouvelle-campagne--chapitre-01.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-02.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-03.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-04.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-05.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-06.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-07.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-08.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-09.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-10.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-11.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-12.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-13.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-14.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-15.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-16.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-17.txt": "Nouvelle Campagne",
  "nouvelle-campagne--chapitre-18.txt": "Nouvelle Campagne",
  "nouvelle-campagne.txt": "Nouvelle Campagne",
  "pot-bouille--chapitre-01.txt": "Pot-bouille",
  "pot-bouille--chapitre-02.txt": "Pot-bouille",
  "pot-bouille--chapitre-03.txt": "Pot-bouille",
  "pot-bouille--chapitre-04.txt": "Pot-bouille",
  "pot-bouille--chapitre-05.txt": "Pot-bouille",
  "pot-bouille--chapitre-06.txt": "Pot-bouille",
  "pot-bouille--chapitre-07.txt": "Pot-bouille",
  "pot-bouille--chapitre-08.txt": "Pot-bouille",
  "pot-bouille--chapitre-09.txt": "Pot-bouille",
  "pot-bouille--chapitre-10.txt": "Pot-bouille",
  "pot-bouille--chapitre-11.txt": "Pot-bouille",
  "pot-bouille--chapitre-12.txt": "Pot-bouille",
  "pot-bouille--chapitre-13.txt": "Pot-bouille",
  "pot-bouille--chapitre-14.txt": "Pot-bouille",
  "pot-bouille--chapitre-15.txt": "Pot-bouille",
  "pot-bouille--chapitre-16.txt": "Pot-bouille",
  "pot-bouille--chapitre-17.txt": "Pot-bouille",
  "pot-bouille--chapitre-18.txt": "Pot-bouille",
  "pot-bouille.txt": "Pot-bouille",
  "pour-une-nuit-damour--chapitre-01.txt": "Pour une Nuit D’amour",
  "pour-une-nuit-damour--chapitre-02.txt": "Pour une Nuit D’amour",
  "pour-une-nuit-damour--chapitre-03.txt": "Pour une Nuit D’amour",
  "pour-une-nuit-damour--chapitre-04.txt": "Pour une Nuit D’amour",
  "pour-une-nuit-damour--chapitre-05.txt": "Pour une Nuit D’amour",
  "pour-une-nuit-damour.txt": "Pour une Nuit D’amour",
  "religion.txt": "Religion",
  "son-excellence-eugene-rougon--chapitre-01.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-02.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-03.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-04.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-05.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-06.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-07.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-08.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-09.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-10.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-11.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-12.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-13.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon--chapitre-14.txt":
    "Son Excellence Eugène Rougon",
  "son-excellence-eugene-rougon.txt": "Son Excellence Eugène Rougon",
  "therese-raquin--chapitre-01.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-02.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-03.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-04.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-05.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-06.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-07.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-08.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-09.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-10.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-11.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-12.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-13.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-14.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-15.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-16.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-17.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-18.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-19.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-20.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-21.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-22.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-23.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-24.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-25.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-26.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-27.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-28.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-29.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-30.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-31.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-32.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-33.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-34.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-35.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-36.txt": "Thérèse Raquin",
  "therese-raquin--chapitre-37.txt": "Thérèse Raquin",
  "therese-raquin-polemiques--chapitre-01.txt": "Thérèse Raquin (polémiques)",
  "therese-raquin-polemiques--chapitre-02.txt": "Thérèse Raquin (polémiques)",
  "therese-raquin-polemiques--chapitre-03.txt": "Thérèse Raquin (polémiques)",
  "therese-raquin-polemiques.txt": "Thérèse Raquin (polémiques)",
  "therese-raquin.txt": "Thérèse Raquin",
  "une-campagne--chapitre-01.txt": "Une Campagne",
  "une-campagne--chapitre-02.txt": "Une Campagne",
  "une-campagne--chapitre-03.txt": "Une Campagne",
  "une-campagne--chapitre-04.txt": "Une Campagne",
  "une-campagne--chapitre-05.txt": "Une Campagne",
  "une-campagne--chapitre-06.txt": "Une Campagne",
  "une-campagne--chapitre-07.txt": "Une Campagne",
  "une-campagne--chapitre-08.txt": "Une Campagne",
  "une-campagne--chapitre-09.txt": "Une Campagne",
  "une-campagne--chapitre-10.txt": "Une Campagne",
  "une-campagne--chapitre-11.txt": "Une Campagne",
  "une-campagne--chapitre-12.txt": "Une Campagne",
  "une-campagne--chapitre-13.txt": "Une Campagne",
  "une-campagne--chapitre-14.txt": "Une Campagne",
  "une-campagne--chapitre-15.txt": "Une Campagne",
  "une-campagne--chapitre-16.txt": "Une Campagne",
  "une-campagne--chapitre-17.txt": "Une Campagne",
  "une-campagne--chapitre-18.txt": "Une Campagne",
  "une-campagne--chapitre-19.txt": "Une Campagne",
  "une-campagne--chapitre-20.txt": "Une Campagne",
  "une-campagne--chapitre-21.txt": "Une Campagne",
  "une-campagne--chapitre-22.txt": "Une Campagne",
  "une-campagne--chapitre-23.txt": "Une Campagne",
  "une-campagne--chapitre-24.txt": "Une Campagne",
  "une-campagne--chapitre-25.txt": "Une Campagne",
  "une-campagne--chapitre-26.txt": "Une Campagne",
  "une-campagne--chapitre-27.txt": "Une Campagne",
  "une-campagne--chapitre-28.txt": "Une Campagne",
  "une-campagne--chapitre-29.txt": "Une Campagne",
  "une-campagne--chapitre-30.txt": "Une Campagne",
  "une-campagne--chapitre-31.txt": "Une Campagne",
  "une-campagne--chapitre-32.txt": "Une Campagne",
  "une-campagne--chapitre-33.txt": "Une Campagne",
  "une-campagne--chapitre-34.txt": "Une Campagne",
  "une-campagne--chapitre-35.txt": "Une Campagne",
  "une-campagne--chapitre-36.txt": "Une Campagne",
  "une-campagne--chapitre-37.txt": "Une Campagne",
  "une-campagne--chapitre-38.txt": "Une Campagne",
  "une-campagne--chapitre-39.txt": "Une Campagne",
  "une-campagne--chapitre-40.txt": "Une Campagne",
  "une-campagne.txt": "Une Campagne",
  "une-farce.txt": "Une Farce",
  "une-page-damour--chapitre-01.txt": "Une Page d'Amour",
  "une-page-damour--chapitre-02.txt": "Une Page d'Amour",
  "une-page-damour--chapitre-03.txt": "Une Page d'Amour",
  "une-page-damour--chapitre-04.txt": "Une Page d'Amour",
  "une-page-damour--chapitre-05.txt": "Une Page d'Amour",
  "une-page-damour.txt": "Une Page d'Amour",
  "vision.txt": "Vision",
  "zola--chapitre-01.txt": "Zola",
  "zola--chapitre-02.txt": "Zola",
  "zola--chapitre-03.txt": "Zola",
  "zola--chapitre-04.txt": "Zola",
  "zola--chapitre-05.txt": "Zola",
  "zola.txt": "Zola",
}

export default ZOLA_TITLES
